@startuml uml
left to right direction
skinparam dpi 300
skinparam DefaultFontName "Readex Pro Deca"

:Registered user: as ruser
:New user: as user

rectangle {
	usecase "Log in" as login
	usecase "Register\naccount" as register
	usecase "Authenticate\nuser" as auth
	usecase "Input\nvalidation" as input

	usecase "Create post" as createpost
	usecase "View posts" as viewposts
	usecase "Search post" as searchpost
	usecase "View profile" as viewprofile
	usecase "Log out" as logout

	login .>> auth: <font size=11><<include>></font>
	register .>> auth: <font size=11><<include>></font>

	register ..>> input: <font size=11><<include>></font>
	login ..>> input: <font size=11><<include>></font>

	rectangle Database {
		' should have session table, user table, and post table
		database "Sessions table" as sessions #pink
		database "Users table" as users #lightgreen
		database "Posts table" as posts #lightblue

		login -->> sessions
		register -->> sessions
		register -->> users
		createpost -->> posts
		viewposts <<-- posts
		searchpost <<-- posts
		viewprofile <<-- users
		viewprofile <<-- posts
		logout -->> sessions
	}
}

ruser ->> user

user -->> register
ruser -->> login
ruser -->> createpost
ruser -->> searchpost
ruser -->> viewposts
ruser -->> viewprofile
ruser -->> logout
@enduml